review_version: 5.0

bookname: book
language: ja
booktitle: 自叙伝
aut: ["鳩山 春子"]
adp: ["Kaoru Mori"]

date: 2026-07-31
history: [["2026-07-31"]]

debug: true

stylesheet: ["style.css"]
toclevel: 1
secnolevel: 0
toc: true

coverimage: cover_1000x1500.png
titlepage: false

direction: "rtl"

epubmaker:
  htmlext: xhtml

texstyle: ["reviewmacro"]
texdocumentclass: ["review-jsbook", "media=print,paper=a5"]

pdfmaker:
  coverimage: cover-a5.ai
  colophon: true
